hms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('hotel.urls')),

]

hotel/urls.py
from django.urls import path
from .views import RoomListView, BookingList, RoomDetailView, CancelBookingView
#app_name = 'hotel'

urlpatterns = [
    path('room_list/', RoomListView, name='room_list'),
    path('booking_list/', BookingList.as_view(), name='booking_list'),
    path('room/<category>', RoomDetailView.as_view(), name='room_detail'),
    path('booking/cancel/<pk>', CancelBookingView.as_view(),
         name='cancel_booking_view'),
]

hotel/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Room(models.Model):

    ROOM_CATEGORIES = (
        ('YAC', 'AC'),  # (CODE , Display)
        ('NAC', 'NON-AC'),
        ('DEL', 'DELUXE'),
        ('KIN', 'KING'),
        ('QUE', 'QUEEN'),
    )

    number = models.IntegerField()
    category = models.CharField(max_length=3, choices=ROOM_CATEGORIES)
    beds = models.IntegerField()
    capacity = models.IntegerField()

    def __str__(self):
        return f'{self.number}. {self.category} with {self.beds} beds for {self.capacity} people'


class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    def __str__(self):
        return f'{self.user} has booked room {self.room.number} from {self.check_in} to {self.check_out}'

    def get_room_category(self):
        room_categories = dict(self.room.ROOM_CATEGORIES)
        room_category = room_categories.get(self.room.category)
        return room_category

    # def get_cancel_booking_url(self):

hotel/forms.py
from django import forms
import datetime
#from .models import ROOM_CATEGORIES


class AvailabilityForm(forms.Form):
    check_in = forms.DateTimeField(
        required=True, input_formats=["%Y-%m-%dT%H%M", ])
    check_out = forms.DateTimeField(
        required=True, input_formats=["%Y-%m-%dT%H%M", ])

hotel/views.py
from django.shortcuts import render, HttpResponse, reverse, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, FormView, View, DeleteView

from .forms import AvailabilityForm
from .models import *
from .booking_functions.availability import check_availability


def RoomListView(request):
    rooms = Room.objects.all()
    categories = dict(Room.ROOM_CATEGORIES)
    categories_values = categories.values()
    room_list = []
    for category in categories:
        room_category = categories.get(category)
        room_url = reverse('room_detail', kwargs={
            'category': category,
        })
        print(room_url)
        room_list.append((room_category, room_url))
    context = {
        'room_list': room_list,
    }
    return render(request, 'hotel/room_list.html', context)


class BookingList(ListView):
    model = Booking
    template_name = 'hotel/booking_list.html'

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_staff:
            book_list = Booking.objects.all()
            return book_list
        else:
            book_list = Booking.objects.filter(user=self.request.user)
            return book_list


class RoomDetailView(View):
    def get(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        form = AvailabilityForm
        room_list = Room.objects.filter(category=category)
        if len(room_list) > 0:
            room = room_list[0]
            room_category = dict(room.ROOM_CATEGORIES).get(room.category, None)
            context = {
                'category': room_category,
                'form': form,
                'room': room
            }
            return render(self.request, 'hotel/room_detail.html', context)
        else:
            return HttpResponse('Category does not exist')

    def post(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        room_list = Room.objects.filter(category=category)
        form = AvailabilityForm(self.request.POST)

        if form.is_valid():
            data = form.cleaned_data

        available_rooms = []
        for room in room_list:
            if check_availability(room, data['check_in'], data['check_out']):
                available_rooms.append(room)

        if len(available_rooms) > 0:
            room = available_rooms[0]
            booking = Booking.objects.create(
                user=self.request.user,
                room=room,
                check_in=data['check_in'],
                check_out=data['check_out'],
            )
            booking.save()
            return redirect('room_list')
        else:
            return HttpResponse('All of this category of rooms are booked. Try another one or change date')


class CancelBookingView(DeleteView):
    model = Booking
    success_url = reverse_lazy('booking_list')
    template_name = 'hotel/booking_cancel_view.html'

hotel/templates/hotel/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/0fe3899c73.js" crossorigin="anonymous"></script>
    <title>HMS</title>
</head>

<body>

    {% block content %}

    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
</body>

</html>

hotel/templates/hotel/booking_cancel_view.html
{% extends 'hotel/base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid bg-secondary" style="height: 100vh;">
    <div class="row  h-100">
        <div class="col-lg-7 my-auto">
            <img class='img-fluid my-auto d-block img-thumbnail border' src="{% static 'hotel/img/room.jpg' %}"
                alt="...">
        </div>
        <div class="col-lg-5 my-auto">
            <div class=" row">
                <div class="col-12 mx-auto">
                    <a href="{% url 'booking_list' %}" class="my-3 btn btn-danger btn-block">Back to Bookings</a>
                    <div class="jumbotron jumbotron-fluid">
                        <div class="container">
                            <h1 class="display-6 text-center">Cancel your Booking for {{ booking.get_room_category }}
                                Suite Room</h1>
                            <p class="lead text-center">
                                Luxury room with {{ room.beds }} beds and capacity for {{ room.capacity }} people
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-11 mx-auto card py-2">
                    <div class="card-body">
                        <h6>Booking Details:</h6>
                        <p>From: {{ booking.check_in }}</p>
                        <p>To: {{ booking.check_out }}</p>
                    </div>
                    <form method="POST" action="">
                        {% csrf_token %}
                        <!-- Input Div -->
                        <!-- Input Div -->
                        <button type="submit" class="btn btn-warning btn-block">Cancel Booking</button>
                    </form>

                </div>

            </div>

        </div>
    </div>
</div>

{% endblock content %}

hotel/templates/hotel/booking_list.html
{% extends 'hotel/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid bg-secondary">
    <div class="jumbotron jumbotron-fluid  bg-dark text-light">
        <div class="container">
            <h1 class="display-4 text-center">Welcome {{ request.user }}</h1>
            <p class='lead text-center'>These are your bookings</p>
        </div>
    </div>
    <div class="row">
        {% for booking in booking_list %}
        <div class="col-lg-4 col-md-6 col-sm-10">
            <div class="card m-2 shadow-secondary">
                <a href="{% url 'room_detail' category=booking.room.category %}"><img
                        src="{% static 'hotel/img/room.jpg' %}" class="card-img-top" alt="..."></a>
                <div class="card-body">
                    <h5 class="card-title">{{ booking.get_room_category }} Suite</h5>
                    <div class="card-text py-0 my-1">
                        <p class='my-1'><strong>From:</strong> {{ booking.check_in }}</p>
                        <p><strong>To:</strong> {{ booking.check_out }}</p>
                        <p class='my-1'><strong>Beds:</strong> {{ booking.room.beds }}</p>
                        <p><strong>Capacity:</strong> {{ booking.room.capacity }}</p>
                    </div>
                    <a href="{% url 'cancel_booking_view' pk=booking.pk %}"
                        class="btn btn-outline-danger btn-block">Cancel Booking</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

hotel/templates/hotel/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Bookings</a>
            </li>
        </ul>
    </div>
</nav>

hotel/templates/hotel/room_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid bg-secondary" style="height: 100vh;">
    <div class="row  h-100">
        <div class="col-lg-7 my-auto">
            <img class='img-fluid my-auto d-block img-thumbnail border' src="{% static 'hotel/img/room.jpg' %}"
                alt="...">
        </div>
        <div class="col-lg-5 my-auto">
            <div class=" row">
                <div class="col-12 mx-auto">
                    <a href="{% url 'room_list' %}" class="my-3 btn btn-danger btn-block">Back to Room List</a>
                    <div class="jumbotron jumbotron-fluid">
                        <div class="container">
                            <h1 class="display-6 text-center">Book your {{ category }} Suite Room</h1>
                            <p class="lead text-center">
                                Luxury room with {{ room.beds }} beds and capacity for {{ room.capacity }} people
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-11 mx-auto card py-2">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <!-- Input Div -->
                        <div class="form-group">
                            <label for="id_check_in">Check In: </label>
                            <input type="datetime-local" class="form-control" id="id_check_in" name="check_in">
                        </div>
                        <!-- Input Div -->
                        <div class="form-group">
                            <label for="id_check_out">Check Out: </label>
                            <input type="datetime-local" class="form-control" id="id_check_out" name="check_out">
                        </div>
                        <!-- Input Div -->
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>

                </div>

            </div>

        </div>
    </div>
</div>

{% endblock content %}

hotel/templates/hotel/room_list.html
{% extends 'hotel/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid bg-secondary">
    <div class="jumbotron jumbotron-fluid  bg-dark text-light">
        <div class="container">
            <h1 class="display-4 text-center">Hotel</h1>
        </div>
    </div>
    <div class="row">
        {% for room_category, room_url in room_list %}
        <div class="col-lg-4 col-md-6 col-sm-10">
            <div class="card m-2 shadow-secondary">
                <img src="{% static 'hotel/img/room.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ room_category }} Suite</h5>
                    <p class="card-text">

                    </p>
                    <a href="{{ room_url }}" class="btn btn-outline-info btn-block">Book
                        a Room</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}